### ISSUE TITLE
Detected I/O inside the event loop. 

### ISSUE THREAD

**Issue by lilbuh** [Pouzor/freebox_player#10]
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 19:31:13 (10 occurrences)
Last logged: 19:31:13
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for freebox_player doing I/O at custom_components/freebox_player/__init__.py, line 58: requests.get(player_path+code, verify=False)

when in send multiple commands ( comma separated ) to increase volume

quand j envois des commande multiple separé par des virgule pour monter le son

**Comment by Pouzor** [comment]
Thx for the issue, I'm gonna check it today

**Comment by merloose** [comment]
Hi all, 
Same for me here.
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for freebox_player doing I/O at custom_components/freebox_player/__init__.py, line 58: requests.get(player_path+code, verify=False)

**Comment by merloose** [comment]
Hi all
made a pull request which solves the issue. for me at least.
using aync_add_executor_job

**Comment by JohannCR** [comment]
Same here.
@merloose suggestion seems to work for me too fyi

**Comment by Pouzor** [comment]
resolve with #12
